[package]
name = "rsa"
version = "0.1.0"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4"
num-bigint = { version = "0.4.3", features = ["rand"] }
rand = "0.8.5"
num-traits = "0.2"
num-integer = "0.1.45"

